
Vue.component('comm-card', {
    props:['modal_id'],
    data: function () {
        return {
            img_addr: '/img/icons/image.svg',
            img_alt: '',
            heading: '',
            subtitle: '',
            icons : [
                "img/icons/001-absorb.svg",                                                       
                "img/icons/001-house.svg",                                                        
                "img/icons/002-parking.svg",                                                      
                "img/icons/002-sanitary pad.svg",                                                 
                "img/icons/003-menstrual cup.svg",                                                
                "img/icons/003-sunglasses.svg",                                                   
                "img/icons/004-disabled person.svg",                                              
                "img/icons/004-panty.svg",                                                        
                "img/icons/005-blind.svg",                                                        
                "img/icons/005-tampon.svg",                                                       
                "img/icons/006-deaf.svg",                                                         
                "img/icons/006-menstrual cup.svg",                                                
                "img/icons/007-calendar.svg",                                                     
                "img/icons/007-gas station.svg",                                                  
                "img/icons/008-smartwatch.svg",                                                   
                "img/icons/008-soap.svg",                                                         
                "img/icons/009-handwash.svg",                                                     
                "img/icons/009-smartphone.svg",                                                   
                "img/icons/010-medical app.svg",                                                  
                "img/icons/010-toilet paper.svg",                                                 
                "img/icons/011-disabled sign.svg",                                                
                "img/icons/011-secure.svg",                                                       
                "img/icons/012-dumb.svg",                                                         
                "img/icons/012-razor.svg",                                                        
                "img/icons/013-blind.svg",                                                        
                "img/icons/013-sanitary pad.svg",                                                 
                "img/icons/014-pills.svg",                                                        
                "img/icons/014-Walking aid.svg",                                                  
                "img/icons/015-injured.svg",                                                      
                "img/icons/015-wet wipes.svg",                                                    
                "img/icons/016-crippled.svg",                                                     
                "img/icons/016-moisturizing.svg",                                                 
                "img/icons/017-disabled person.svg",                                              
                "img/icons/017-moisturizer.svg",                                                  
                "img/icons/018-Cotton.svg",                                                       
                "img/icons/018-disabled person.svg",                                              
                "img/icons/019-injured.svg",                                                      
                "img/icons/019-tissues.svg",                                                      
                "img/icons/020-vagina.svg",                                                       
                "img/icons/020-walking stick.svg",                                                
                "img/icons/021-cream.svg",                                                        
                "img/icons/021-hospital bed.svg",                                                 
                "img/icons/022-love.svg",                                                         
                "img/icons/022-wheelchair.svg",                                                   
                "img/icons/023-cleanser.svg",                                                     
                "img/icons/023-medical assistance.svg",                                           
                "img/icons/024-dustbin.svg",                                                      
                "img/icons/024-prosthetic.svg",                                                   
                "img/icons/025-crutch.svg",                                                       
                "img/icons/025-hot water bottle.svg",                                             
                "img/icons/026-deodorant.svg",                                                    
                "img/icons/026-walking stick.svg",                                                
                "img/icons/027-be free.svg",                                                      
                "img/icons/027-Walking aid.svg",                                                  
                "img/icons/028-prosthetic.svg",                                                   
                "img/icons/028-washing hands.svg",                                                
                "img/icons/029-car.svg",                                                          
                "img/icons/029-sanitary pad.svg",                                                 
                "img/icons/030-gynecology.svg",                                                   
                "img/icons/030-wheelchair.svg",                                                   
                "img/icons/031-wheelchair.svg",                                                   
                "img/icons/032-braille.svg",                                                      
                "img/icons/033-wheelchair.svg",                                                   
                "img/icons/034-audio book.svg",                                                   
                "img/icons/035-prosthetic.svg",                                                   
                "img/icons/036-prosthetic.svg",                                                   
                "img/icons/037-prosthetic.svg",                                                   
                "img/icons/038-sign language.svg",                                                
                "img/icons/039-stairs.svg",                                                       
                "img/icons/040-tv.svg",                                                           
                "img/icons/041-bus.svg",                                                          
                "img/icons/042-hearing aid.svg",                                                  
                "img/icons/043-wheelchair.svg",                                                   
                "img/icons/044-crutch.svg",                                                       
                "img/icons/045-guide dog.svg",                                                    
                "img/icons/046-hospital.svg",                                                     
                "img/icons/047-disabled person.svg",                                              
                "img/icons/048-disabled person.svg",                                              
                "img/icons/049-wc.svg",                                                           
                "img/icons/050-lift.svg",                                                         
                "img/icons/activity.svg",                                                         
                "img/icons/airplay.svg",                                                          
                "img/icons/alert-circle.svg",                                                     
                "img/icons/alert-octagon.svg",                                                    
                "img/icons/alert-triangle.svg",                                                   
                "img/icons/align-center.svg",                                                     
                "img/icons/align-justify.svg",                                                    
                "img/icons/align-left.svg",                                                       
                "img/icons/align-right.svg",                                                      
                "img/icons/anchor.svg",                                                           
                "img/icons/aperture.svg",                                                         
                "img/icons/archive.svg",                                                          
                "img/icons/arrow-down-circle.svg",                                                
                "img/icons/arrow-down-left.svg",                                                  
                "img/icons/arrow-down-right.svg",                                                 
                "img/icons/arrow-down.svg",                                                       
                "img/icons/arrow-left-circle.svg",                                                
                "img/icons/arrow-left.svg",                                                       
                "img/icons/arrow-right-circle.svg",                                               
                "img/icons/arrow-right.svg",                                                      
                "img/icons/arrow-up-circle.svg",                                                  
                "img/icons/arrow-up-left.svg",                                                    
                "img/icons/arrow-up-right.svg",                                                   
                "img/icons/arrow-up.svg",                                                         
                "img/icons/at-sign.svg",                                                          
                "img/icons/award.svg",                                                            
                "img/icons/bar-chart-2.svg",                                                      
                "img/icons/bar-chart.svg",                                                        
                "img/icons/battery-charging.svg",                                                 
                "img/icons/battery.svg",                                                          
                "img/icons/bell-off.svg",                                                         
                "img/icons/bell.svg",                                                             
                "img/icons/bluetooth.svg",                                                        
                "img/icons/bold.svg",                                                             
                "img/icons/book-open.svg",                                                        
                "img/icons/book.svg",                                                             
                "img/icons/bookmark.svg",                                                         
                "img/icons/box.svg",                                                              
                "img/icons/briefcase.svg",                                                        
                "img/icons/calendar.svg",                                                         
                "img/icons/camera-off.svg",                                                       
                "img/icons/camera.svg",                                                           
                "img/icons/cast.svg",                                                             
                "img/icons/check-circle.svg",                                                     
                "img/icons/check-square.svg",                                                     
                "img/icons/check.svg",                                                            
                "img/icons/chevron-down.svg",                                                     
                "img/icons/chevron-left.svg",                                                     
                "img/icons/chevron-right.svg",                                                    
                "img/icons/chevron-up.svg",                                                       
                "img/icons/chevrons-down.svg",                                                    
                "img/icons/chevrons-left.svg",                                                    
                "img/icons/chevrons-right.svg",                                                   
                "img/icons/chevrons-up.svg",                                                      
                "img/icons/chrome.svg",                                                           
                "img/icons/circle.svg",                                                           
                "img/icons/clipboard.svg",                                                        
                "img/icons/clock.svg",                                                            
                "img/icons/cloud-drizzle.svg",                                                    
                "img/icons/cloud-lightning.svg",                                                  
                "img/icons/cloud-off.svg",                                                        
                "img/icons/cloud-rain.svg",                                                       
                "img/icons/cloud-snow.svg",                                                       
                "img/icons/cloud.svg",                                                            
                "img/icons/code.svg",                                                             
                "img/icons/codepen.svg",                                                          
                "img/icons/codesandbox.svg",                                                      
                "img/icons/coffee.svg",                                                           
                "img/icons/columns.svg",                                                          
                "img/icons/command.svg",                                                          
                "img/icons/compass.svg",                                                          
                "img/icons/copy.svg",                                                             
                "img/icons/corner-down-left.svg",                                                 
                "img/icons/corner-down-right.svg",                                                
                "img/icons/corner-left-down.svg",                                                 
                "img/icons/corner-left-up.svg",                                                   
                "img/icons/corner-right-down.svg",                                                
                "img/icons/corner-right-up.svg",                                                  
                "img/icons/corner-up-left.svg",                                                   
                "img/icons/corner-up-right.svg",                                                  
                "img/icons/cpu.svg",                                                              
                "img/icons/credit-card.svg",                                                      
                "img/icons/crop.svg",                                                             
                "img/icons/crosshair.svg",                                                        
                "img/icons/database.svg",                                                         
                "img/icons/delete.svg",                                                           
                "img/icons/disc.svg",                                                             
                "img/icons/divide-circle.svg",                                                    
                "img/icons/divide-square.svg",                                                    
                "img/icons/divide.svg",                                                           
                "img/icons/dollar-sign.svg",                                                      
                "img/icons/download-cloud.svg",                                                   
                "img/icons/download.svg",                                                         
                "img/icons/dribbble.svg",                                                         
                "img/icons/droplet.svg",                                                          
                "img/icons/edit-2.svg",                                                           
                "img/icons/edit-3.svg",                                                           
                "img/icons/edit.svg",                                                             
                "img/icons/external-link.svg",                                                    
                "img/icons/eye-off.svg",                                                          
                "img/icons/eye.svg",                                                              
                "img/icons/facebook.svg",                                                         
                "img/icons/fast-forward.svg",                                                     
                "img/icons/feather.svg",                                                          
                "img/icons/figma.svg",                                                            
                "img/icons/file-minus.svg",                                                       
                "img/icons/file-plus.svg",                                                        
                "img/icons/file-text.svg",                                                        
                "img/icons/file.svg",                                                             
                "img/icons/files.txt",                                                            
                "img/icons/film.svg",                                                             
                "img/icons/filter.svg",                                                           
                "img/icons/flag.svg",                                                             
                "img/icons/folder-minus.svg",                                                     
                "img/icons/folder-plus.svg",                                                      
                "img/icons/folder.svg",                                                           
                "img/icons/framer.svg",                                                           
                "img/icons/frown.svg",                                                            
                "img/icons/gift.svg",                                                             
                "img/icons/git-branch.svg",                                                       
                "img/icons/git-commit.svg",                                                       
                "img/icons/git-merge.svg",                                                        
                "img/icons/git-pull-request.svg",                                                 
                "img/icons/github.svg",                                                           
                "img/icons/gitlab.svg",                                                           
                "img/icons/globe.svg",                                                            
                "img/icons/grid.svg",                                                             
                "img/icons/hard-drive.svg",                                                       
                "img/icons/hash.svg",                                                             
                "img/icons/headphones.svg",                                                       
                "img/icons/heart.svg",                                                            
                "img/icons/help-circle.svg",                                                      
                "img/icons/hexagon.svg",                                                          
                "img/icons/home.svg",                                                             
                "img/icons/image.svg",                                                            
                "img/icons/inbox.svg",                                                            
                "img/icons/info.svg",                                                             
                "img/icons/instagram.svg",                                                        
                "img/icons/italic.svg",                                                           
                "img/icons/key.svg",                                                              
                "img/icons/layers.svg",                                                           
                "img/icons/layout.svg",                                                           
                "img/icons/life-buoy.svg",                                                        
                "img/icons/link-2.svg",                                                           
                "img/icons/link.svg",                                                             
                "img/icons/linkedin.svg",                                                         
                "img/icons/list.svg",                                                             
                "img/icons/loader.svg",                                                           
                "img/icons/lock.svg",                                                             
                "img/icons/log-in.svg",                                                           
                "img/icons/log-out.svg",                                                          
                "img/icons/mail.svg",                                                             
                "img/icons/map-pin.svg",                                                          
                "img/icons/map.svg",                                                              
                "img/icons/maximize-2.svg",                                                       
                "img/icons/maximize.svg",                                                         
                "img/icons/meh.svg",                                                              
                "img/icons/menu.svg",                                                             
                "img/icons/message-circle.svg",                                                   
                "img/icons/message-square.svg",                                                   
                "img/icons/mic-off.svg",                                                          
                "img/icons/mic.svg",                                                              
                "img/icons/minimize-2.svg",                                                       
                "img/icons/minimize.svg",                                                         
                "img/icons/minus-circle.svg",                                                     
                "img/icons/minus-square.svg",                                                     
                "img/icons/minus.svg",                                                            
                "img/icons/monitor.svg",                                                          
                "img/icons/moon.svg",                                                             
                "img/icons/more-horizontal.svg",                                                  
                "img/icons/more-vertical.svg",                                                    
                "img/icons/mouse-pointer.svg",                                                    
                "img/icons/move.svg",                                                             
                "img/icons/music.svg",                                                            
                "img/icons/navigation-2.svg",                                                     
                "img/icons/navigation.svg",                                                       
                "img/icons/octagon.svg",                                                          
                "img/icons/package.svg",                                                          
                "img/icons/paperclip.svg",                                                        
                "img/icons/pause-circle.svg",                                                     
                "img/icons/pause.svg",                                                            
                "img/icons/pen-tool.svg",                                                         
                "img/icons/percent.svg",                                                          
                "img/icons/phone-call.svg",                                                       
                "img/icons/phone-forwarded.svg",                                                  
                "img/icons/phone-incoming.svg",                                                   
                "img/icons/phone-missed.svg",                                                     
                "img/icons/phone-off.svg",                                                        
                "img/icons/phone-outgoing.svg",                                                   
                "img/icons/phone.svg",                                                            
                "img/icons/pie-chart.svg",                                                        
                "img/icons/play-circle.svg",                                                      
                "img/icons/play.svg",                                                             
                "img/icons/plus-circle.svg",                                                      
                "img/icons/plus-square.svg",                                                      
                "img/icons/plus.svg",                                                             
                "img/icons/pocket.svg",                                                           
                "img/icons/power.svg",                                                            
                "img/icons/printer.svg",                                                          
                "img/icons/radio.svg",                                                            
                "img/icons/refresh-ccw.svg",                                                      
                "img/icons/refresh-cw.svg",                                                       
                "img/icons/repeat.svg",                                                           
                "img/icons/rewind.svg",                                                           
                "img/icons/rotate-ccw.svg",                                                       
                "img/icons/rotate-cw.svg",                                                        
                "img/icons/rss.svg",                                                              
                "img/icons/save.svg",                                                             
                "img/icons/scissors.svg",                                                         
                "img/icons/search.svg",                                                           
                "img/icons/send.svg",                                                             
                "img/icons/server.svg",                                                           
                "img/icons/settings.svg",                                                         
                "img/icons/share-2.svg",                                                          
                "img/icons/share.svg",                                                            
                "img/icons/shield-off.svg",                                                       
                "img/icons/shield.svg",                                                           
                "img/icons/shopping-bag.svg",                                                     
                "img/icons/shopping-cart.svg",                                                    
                "img/icons/shuffle.svg",                                                          
                "img/icons/sidebar.svg",                                                          
                "img/icons/skip-back.svg",                                                        
                "img/icons/skip-forward.svg",                                                     
                "img/icons/slack.svg",                                                            
                "img/icons/slash.svg",                                                            
                "img/icons/sliders.svg",                                                          
                "img/icons/smartphone.svg",                                                       
                "img/icons/smile.svg",                                                            
                "img/icons/speaker.svg",                                                          
                "img/icons/square.svg",                                                           
                "img/icons/star.svg",                                                             
                "img/icons/stop-circle.svg",                                                      
                "img/icons/sun.svg",                                                              
                "img/icons/sunrise.svg",                                                          
                "img/icons/sunset.svg",                                                           
                "img/icons/tablet.svg",                                                           
                "img/icons/tag.svg",                                                              
                "img/icons/target.svg",                                                           
                "img/icons/terminal.svg",                                                         
                "img/icons/thermometer.svg",                                                      
                "img/icons/thumbs-down.svg",                                                      
                "img/icons/thumbs-up.svg",                                                        
                "img/icons/toggle-left.svg",                                                      
                "img/icons/toggle-right.svg",                                                     
                "img/icons/tool.svg",                                                             
                "img/icons/trash-2.svg",                                                          
                "img/icons/trash.svg",                                                            
                "img/icons/trello.svg",                                                           
                "img/icons/trending-down.svg",                                                    
                "img/icons/trending-up.svg",                                                      
                "img/icons/triangle.svg",                                                         
                "img/icons/truck.svg",                                                            
                "img/icons/tv.svg",                                                               
                "img/icons/twitch.svg",                                                           
                "img/icons/twitter.svg",                                                          
                "img/icons/type.svg",                                                             
                "img/icons/umbrella.svg",                                                         
                "img/icons/underline.svg",                                                        
                "img/icons/unlock.svg",                                                           
                "img/icons/upload-cloud.svg",                                                     
                "img/icons/upload.svg",                                                           
                "img/icons/user-check.svg",                                                       
                "img/icons/user-minus.svg",                                                       
                "img/icons/user-plus.svg",                                                        
                "img/icons/user-x.svg",                                                           
                "img/icons/user.svg",                                                             
                "img/icons/users.svg",                                                            
                "img/icons/video-off.svg",                                                        
                "img/icons/video.svg",                                                            
                "img/icons/voicemail.svg",                                                        
                "img/icons/volume-1.svg",                                                         
                "img/icons/volume-2.svg",                                                         
                "img/icons/volume-x.svg",                                                         
                "img/icons/volume.svg",                                                           
                "img/icons/watch.svg",                                                            
                "img/icons/wifi-off.svg",                                                         
                "img/icons/wifi.svg",                                                             
                "img/icons/wind.svg",                                                             
                "img/icons/x-circle.svg",                                                         
                "img/icons/x-octagon.svg",                                                        
                "img/icons/x-square.svg",                                                         
                "img/icons/x.svg",                                                                
                "img/icons/youtube.svg",                                                          
                "img/icons/zap-off.svg",                                                          
                "img/icons/zap.svg",                                                              
                "img/icons/zoom-in.svg",                                                          
                "img/icons/zoom-out.svg",
            ],
        }
    },
    template: `
    <div class="card">
        <b-button v-b-modal=modal_id class="modal-button">
            <img v-bind:src="img_addr" class="card-img-top" :alt=img_alt>
        </b-button>

        <div class="card-body">
        <h5 class="text-center d-print-only">{{ heading }}</h5>
        <input v-model="heading" maxlength="12" class="heading-input text-center d-print-none">
        <p class="text-center d-print-only">{{ subtitle }}</p>
        <input v-model="subtitle" maxlength="19" class="text-center d-print-none">
        </div>


        <b-modal :id="modal_id" size="lg" title="Select a new icon" centered ok-only scrollable  no-stacking>
            <div class="container">
                <div class="row">
                    <div v-for="icon in icons" :key="icon.message" class="col">
                            <b-form-radio v-model="img_addr"  name="icons" :value="icon" >
                                <img :src="icon" :alt=img_alt>
                            </b-form-radio>
                    </div>
                </div>
            </div>
        </b-modal>
    </div>
    `
})

var app = new Vue({
    el: '#app',
})