import html2canvas from 'html2canvas-pro'
import { exportFilename, QUALITY_SCALE, type ExportQuality } from './exportFilename'

/**
 * Captures a DOM element as a PNG image and triggers a download.
 *
 * Uses `html2canvas` to rasterise the element at a pixel ratio determined
 * by the requested quality, converts the resulting canvas to a `Blob`, and
 * initiates a download via a synthetic `<a>` click.
 *
 * Callers are responsible for:
 *  - ensuring the element is visible and fully laid out (not `display:none`)
 *  - neutralising any transient UI chrome (selection rings, zoom transforms)
 *    before capture, and restoring it afterwards
 *  - presenting a loading state while this promise is pending, since the
 *    high-quality capture can take a second or two
 *
 * @param canvasElement The DOM node to capture.
 * @param title The chart title — sanitised and date-stamped to form the
 *   download filename (e.g. `My Chart` → `my-chart-2026-07-16.png`).
 * @param quality Pixel-ratio level; defaults to `'normal'` (scale 2).
 *
 * @throws {Error} if the PNG blob cannot be generated by the browser.
 */
export async function exportToPng(
  canvasElement: HTMLElement,
  title: string,
  quality: ExportQuality = 'normal',
): Promise<void> {
  const scale = QUALITY_SCALE[quality]

  // Ensure web fonts are fully loaded before capture to avoid fallback-font
  // text being baked into the PNG.
  if (typeof document !== 'undefined' && 'fonts' in document) {
    try {
      await (document as Document & { fonts: { ready: Promise<unknown> } }).fonts.ready
    } catch {
      // Non-critical — proceed with capture even if font API fails
    }
  }

  const rendered = await html2canvas(canvasElement, {
    scale,
    useCORS: true,
    // The A4 page already carries its own background via the theme; force a
    // solid white so transparent gaps never leak through in the PNG.
    backgroundColor: '#ffffff',
    logging: false,
    // Skip the synthetic print footer and any off-screen chrome.
    ignoreElements: (el) => el.classList?.contains('print-footer'),
  })

  const blob = await new Promise<Blob | null>((resolve) =>
    rendered.toBlob(resolve, 'image/png'),
  )

  if (!blob) {
    throw new Error('Failed to generate PNG image. Please try again.')
  }

  const filename = exportFilename(title, 'png')
  triggerDownload(blob, filename)
}

/**
 * Trigger a browser download for an in-memory blob.
 *
 * Creates a temporary object URL, appends an anchor, clicks it, then cleans
 * up. The cleanup is scheduled on the next tick so the download has time
 * to start in every browser.
 */
function triggerDownload(blob: Blob, filename: string): void {
  const url = URL.createObjectURL(blob)
  const link = document.createElement('a')
  link.href = url
  link.download = filename
  link.rel = 'noopener'
  // The link must be in the document for Firefox to honour the click.
  link.style.display = 'none'
  document.body.appendChild(link)
  link.click()
  document.body.removeChild(link)

  // Revoke on a delay so the download stream has fully initialised.
  window.setTimeout(() => URL.revokeObjectURL(url), 1000)
}
