import html2canvas from 'html2canvas-pro'
import { exportFilename, QUALITY_SCALE, type ExportQuality } from './exportFilename'

/**
 * Captures the chart canvas as a PNG image and triggers a download.
 *
 * CSS transforms (zoom) are temporarily cleared before capture so the
 * element renders at its natural 1:1 pixel size. This ensures the output
 * image has the correct A4 aspect ratio (1.414:1) at the requested DPI.
 *
 * @param canvasElement The `.canvas-page` DOM node to capture.
 * @param title Chart title — used to build the download filename.
 * @param quality Pixel-ratio level (draft=1, normal=2, high=3).
 *   Higher values produce crisper output at the cost of a larger file.
 *
 * @throws {Error} if the PNG blob cannot be generated by the browser.
 */
export async function exportToPng(
  canvasElement: HTMLElement,
  title: string,
  quality: ExportQuality = 'normal',
): Promise<void> {
  const scale = QUALITY_SCALE[quality]

  // Temporarily strip CSS transforms so html2canvas captures the element
  // at its natural (un-zoomed) pixel size, preserving the correct aspect ratio.
  const originalTransform = canvasElement.style.transform
  const originalTransformOrigin = canvasElement.style.transformOrigin
  canvasElement.style.transform = 'none'
  canvasElement.style.transformOrigin = ''

  // Wait for fonts before rasterising
  if (typeof document !== 'undefined' && 'fonts' in document) {
    try {
      await (document as Document & { fonts: { ready: Promise<unknown> } }).fonts.ready
    } catch {
      // Non-critical
    }
  }

  try {
    const rendered = await html2canvas(canvasElement, {
      scale,
      useCORS: true,
      backgroundColor: '#ffffff',
      logging: false,
      ignoreElements: (el) => el.classList?.contains('print-footer'),
    })

    // Sanity check — abort if the capture produced nothing
    if (rendered.width < 10 || rendered.height < 10) {
      throw new Error('Captured chart is too small — please try again.')
    }

    const blob = await new Promise<Blob | null>((resolve) =>
      rendered.toBlob(resolve, 'image/png'),
    )

    if (!blob) {
      throw new Error('Failed to generate PNG image. Please try again.')
    }

    const filename = exportFilename(title, 'png')
    triggerDownload(blob, filename)
  } finally {
    // Restore the original transform
    canvasElement.style.transform = originalTransform
    canvasElement.style.transformOrigin = originalTransformOrigin
  }
}

/**
 * Trigger a browser download for an in-memory blob.
 */
function triggerDownload(blob: Blob, filename: string): void {
  const url = URL.createObjectURL(blob)
  const link = document.createElement('a')
  link.href = url
  link.download = filename
  link.rel = 'noopener'
  link.style.display = 'none'
  document.body.appendChild(link)
  link.click()
  document.body.removeChild(link)

  // Revoke on a delay so the download stream has fully initialised.
  window.setTimeout(() => URL.revokeObjectURL(url), 1000)
}
